version: "3"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "7576:7576"
    volumes:
      - /data/wglv_1/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
